name: Generate Metrics

on:
  schedule:
    - cron: "0 18 * * *"  # 日本時間 3:00
  workflow_dispatch:

jobs:
  metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Base Stats
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: assets/metrics-base.svg
          base: header, activity, community, repositories
          base_indepth: yes
          config_timezone: Asia/Tokyo
          config_display: large

      - name: Languages
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_TOKEN }}
          filename: assets/metrics-languages.svg
          base: ""
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          config_timezone: Asia/Tokyo
